spring.datasource.url=jdbc:mysql://localhost:3306/afterclass
spring.datasource.username=root
spring.datasource.password=root
spring.datasourse.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.mvc.date-format=yyyy/mm/dd
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=8MB

spring.mail.host=smtp.mail.yahoo.com
spring.mail.port=465
spring.mail.username=afterclassteam4@gmail.com
spring.mail.password=team4egg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enabled=true




